
06/02/21, 08:54:23 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fd3dc56a550>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : false          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 08:54:25 PM: 
   Program interrupted by KeyboardInterrupt!

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 255, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 08:54:25 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 08:54:29 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f6744729550>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : false          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 08:54:30 PM: 
   Program interrupted by KeyboardInterrupt!

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 255, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 08:54:30 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 08:54:35 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f6396cc9550>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 08:54:54 PM: 
   Program interrupted by KeyboardInterrupt!

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 255, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 08:54:54 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:03:40 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fed827eb550>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 09:03:52 PM: 
   Program interrupted by KeyboardInterrupt!

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 255, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 09:03:52 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:06:28 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f03f3120550>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 09:06:40 PM: 
   Program interrupted by KeyboardInterrupt!

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 255, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 09:06:40 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:22:52 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f81f5267b20>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:23:00 PM: 
    Acquiring paginated list of pull requests.

06/02/21, 09:23:02 PM: 
    Acquiring pull request data and paginated list of commits.

06/02/21, 09:23:03 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 172, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 299, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 851, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 933, in get_PR_info
    cur_pr      = pr_paged_list[index]
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:23:03 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:23:05 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fc62728bb20>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:23:38 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 172, in main
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 260, in exe_menu
KeyboardInterrupt

06/02/21, 09:23:38 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:23:41 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f495febab20>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv

06/02/21, 09:23:48 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 171, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 259, in exe_menu
    op_choice = input("\nExecute ")
KeyboardInterrupt

06/02/21, 09:23:48 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:24:30 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f43cb38fb20>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:24:55 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:24:55 PM: 
    Acquiring issue data.

06/02/21, 09:24:59 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 171, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 292, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 655, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 565, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 532, in request
    settings = self.merge_environment_settings(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 711, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "/usr/lib/python3.9/site-packages/requests/utils.py", line 776, in get_environ_proxies
    if should_bypass_proxies(url, no_proxy=no_proxy):
  File "/usr/lib/python3.9/site-packages/requests/utils.py", line 760, in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "/usr/lib/python3.9/urllib/request.py", line 2525, in proxy_bypass_environment
    proxies = getproxies_environment()
  File "/usr/lib/python3.9/urllib/request.py", line 2508, in getproxies_environment
    for name, value in os.environ.items():
  File "/usr/lib/python3.9/_collections_abc.py", line 850, in __iter__
    yield (key, self._mapping[key])
  File "/usr/lib/python3.9/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.9/os.py", line 754, in encode
    def encode(value):
KeyboardInterrupt

06/02/21, 09:24:59 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:33:21 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f66a3c9fbe0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:33:35 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    csv_choice = input( CSV_PROMPT )
KeyboardInterrupt

06/02/21, 09:33:35 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:33:40 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fe4b334abe0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:33:43 PM: 
Attempting program start.

06/02/21, 09:33:43 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:33:43 PM: 
    Acquiring issue data.

06/02/21, 09:33:45 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 578, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:33:45 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:40:18 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f41734c6bb0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:40:24 PM: 
Attempting program start.

06/02/21, 09:40:24 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:40:24 PM: 
    Acquiring issue data.

06/02/21, 09:40:49 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 561, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:40:49 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:47:03 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fe3c44c0c70>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:47:05 PM: 
Attempting program start.

06/02/21, 09:47:05 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 282, in exe_menu
    paged_metalist = get_paginated_lists( session, repo_str,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 782, in get_paginated_lists
    log_and_print( "PAGED_ISSUES", "INFO", logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 1112, in log_and_print
    log_msg = log_dict[msg_format]
KeyError: 'PAGED_ISSUES'

06/02/21, 09:47:05 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:47:35 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f504dbb7c70>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:47:37 PM: 
Attempting program start.

06/02/21, 09:47:37 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:47:37 PM: 
    Acquiring issue data.

06/02/21, 09:47:49 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 582, in get_issue_info
    for comment in comments_paged_list:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:47:49 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:58:31 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fa93af77ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:58:35 PM: 
Attempting program start.

06/02/21, 09:58:36 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:58:36 PM: 
   Complete!

06/02/21, 09:58:36 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 09:58:36 PM: 
   Complete!

06/02/21, 09:58:36 PM: 
    Acquiring issue data.

06/02/21, 09:58:39 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 578, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:58:39 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:58:58 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f2390ef3ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:59:00 PM: 
Attempting program start.

06/02/21, 09:59:01 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:59:01 PM: 
   Complete!

06/02/21, 09:59:01 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 09:59:01 PM: 
   Complete!

06/02/21, 09:59:01 PM: 
    Acquiring issue data.

06/02/21, 09:59:03 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 578, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:59:03 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 09:59:30 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f38af0a4eb0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 09:59:31 PM: 
Attempting program start.

06/02/21, 09:59:31 PM: 
    Acquiring paginated list of issues.

06/02/21, 09:59:31 PM: 
   Complete!

06/02/21, 09:59:31 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 09:59:31 PM: 
   Complete!

06/02/21, 09:59:32 PM: 
    Acquiring issue data.

06/02/21, 09:59:34 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 651, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 561, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 09:59:34 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:10:34 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f7332604f70>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:10:37 PM: 
Attempting program start.

06/02/21, 10:10:37 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:10:37 PM: 
    Complete!

06/02/21, 10:10:37 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 10:10:37 PM: 
    Complete!

06/02/21, 10:10:37 PM: 
    Getting issue data...

06/02/21, 10:10:37 PM: 
    Acquiring issue data.

06/02/21, 10:10:43 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 653, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 580, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 10:10:43 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:12:38 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7efd72835ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:12:40 PM: 
Attempting program start.

06/02/21, 10:12:40 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:12:40 PM: 
    Complete!

06/02/21, 10:12:40 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 10:12:40 PM: 
    Complete!

06/02/21, 10:12:40 PM: 
    Getting issue data...

06/02/21, 10:12:44 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 650, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 560, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 10:12:44 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:13:13 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f79f9dc1ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:13:16 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    csv_choice = input( CSV_PROMPT )
KeyboardInterrupt

06/02/21, 10:13:16 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:13:23 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f76ab06dee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:13:24 PM: 
Attempting program start.

06/02/21, 10:13:25 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:13:25 PM: 
    Acquiring paginated list of pull requests...

06/02/21, 10:13:25 PM: 
    Complete!

06/02/21, 10:13:27 PM: 
    Acquiring pull request data and paginated list of commits.

06/02/21, 10:13:33 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 296, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 843, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 927, in get_PR_info
    if cur_pr.merged == True:
  File "/home/j/.local/lib/python3.9/site-packages/github/PullRequest.py", line 259, in merged
    self._completeIfNotSet(self._merged)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 10:13:33 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:13:34 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fa83a9d5ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:13:36 PM: 
Attempting program start.

06/02/21, 10:13:36 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:13:36 PM: 
    Complete!

06/02/21, 10:13:37 PM: 
    Getting issue data...

06/02/21, 10:13:38 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 173, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 290, in exe_menu
    get_issue_json( session, issue_paged_list, row_quant, logger,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 650, in get_issue_json
    issue_metalist = get_issue_info( session, issue_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 577, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

06/02/21, 10:13:38 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:13:56 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f0a8f052ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:13:58 PM: 
Attempting program start.

06/02/21, 10:13:58 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:13:58 PM: 
        Complete!

06/02/21, 10:13:58 PM: 
    Getting issue data...

06/02/21, 10:14:36 PM: 
    Writing issue data to JSON.

06/02/21, 10:14:36 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:16:59 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f5d4b8c1ee0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:17:00 PM: 
Attempting program start.

06/02/21, 10:17:01 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:17:01 PM: 
        Complete!

06/02/21, 10:17:01 PM: 
    Getting issue data...

06/02/21, 10:17:39 PM: 
    Writing list of issue data to JSON...

06/02/21, 10:17:39 PM: 
        Complete!

06/02/21, 10:17:39 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


06/02/21, 10:18:27 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f32e66ab070>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


06/02/21, 10:18:29 PM: 
Attempting program start.

06/02/21, 10:18:29 PM: 
    Acquiring paginated list of issues.

06/02/21, 10:18:29 PM: 
        Complete!

06/02/21, 10:18:29 PM: 
    Getting issue data...

06/02/21, 10:19:09 PM: 
        Complete!

06/02/21, 10:19:09 PM: 
    Writing list of issue data to JSON...

06/02/21, 10:19:09 PM: 
        Complete!

06/02/21, 10:19:09 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:05:21:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f19e75adca0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:05:27:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:05:27:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:05:27:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:05:27:%f AM:         Complete!

Thu, 06/03/21, 11:05:28:%f AM: 
    Getting PR data

Thu, 06/03/21, 11:05:39:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 976, in get_PR_info
    if pr_commits.totalCount > 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:05:39:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:06:12:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7ff3fc408c70>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:06:14:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:06:14:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:06:14:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:06:14:%f AM: 
        Complete!

Thu, 06/03/21, 11:06:16:%f AM: 
    Getting PR data

Thu, 06/03/21, 11:06:33:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 935, in get_PR_info
    if cur_pr.merged == True:
  File "/home/j/.local/lib/python3.9/site-packages/github/PullRequest.py", line 259, in merged
    self._completeIfNotSet(self._merged)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:06:33:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:06:58:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f05c2cc3c70>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:06:59:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:06:59:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:06:59:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:06:59:%f AM: 
        Complete!

Thu, 06/03/21, 11:07:01:%f AM: 
    Getting PR data

Thu, 06/03/21, 11:08:42:%f AM: 
        Complete!

Thu, 06/03/21, 11:08:42:%f AM: 
    Writing list of PR data to JSON...

Thu, 06/03/21, 11:08:42:%f AM: 
        Complete!

Thu, 06/03/21, 11:08:42:%f AM: 
    Getting commit data...

Thu, 06/03/21, 11:09:02:%f AM: 
        Complete!

Thu, 06/03/21, 11:09:02:%f AM: 
    Writing list of commit data to JSON...

Thu, 06/03/21, 11:09:02:%f AM: 
        Complete!

Thu, 06/03/21, 11:09:02:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:12:56:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fb316742d90>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:12:58:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:12:58:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:12:58:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:12:58:%f AM: 
        Complete!

Thu, 06/03/21, 11:12:59:%f AM: 
    Getting PR data

Thu, 06/03/21, 11:13:44:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 976, in get_PR_info
    if pr_commits.totalCount > 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:13:44:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:13:46:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fd7b2142d60>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:13:47:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:13:47:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:13:47:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:13:47:%f AM: 
        Complete!

Thu, 06/03/21, 11:13:48:%f AM: 
    Getting pull request data...

Thu, 06/03/21, 11:14:07:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 983, in get_PR_info
    most_recent_commit = pr_commits[last_commit_position]
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:14:07:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:14:27:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7fe00523ad60>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:14:28:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:14:28:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:14:28:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:14:28:%f AM: 
        Complete!

Thu, 06/03/21, 11:14:28:%f AM: 
    Getting pull request data...

Thu, 06/03/21, 11:14:33:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 935, in get_PR_info
    if cur_pr.merged == True:
  File "/home/j/.local/lib/python3.9/site-packages/github/PullRequest.py", line 259, in merged
    self._completeIfNotSet(self._merged)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:14:33:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:14:42:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f42c7b99d60>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:14:43:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:14:43:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:14:43:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:14:43:%f AM: 
        Complete!

Thu, 06/03/21, 11:14:44:%f AM: 
    Getting pull request data...

Thu, 06/03/21, 11:15:09:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 935, in get_PR_info
    if cur_pr.merged == True:
  File "/home/j/.local/lib/python3.9/site-packages/github/PullRequest.py", line 259, in merged
    self._completeIfNotSet(self._merged)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:15:09:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Thu, 06/03/21, 11:15:55:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f669221fd60>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Thu, 06/03/21, 11:15:57:%f AM: 
Attempting program start...

Thu, 06/03/21, 11:15:57:%f AM: 
    Getting paginated list of issues...

Thu, 06/03/21, 11:15:57:%f AM: 
    Getting paginated list of pull requests...

Thu, 06/03/21, 11:15:57:%f AM: 
        Complete!

Thu, 06/03/21, 11:15:59:%f AM: 
    Getting pull request data...

Thu, 06/03/21, 11:15:59:%f AM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 122, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 303, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 853, in get_PR_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 933, in get_PR_info
    cur_pr      = pr_paged_list[index]
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Thu, 06/03/21, 11:15:59:%f AM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 12:47:00 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f09de025130>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 12:47:05 PM: 
Attempting program start...

Fri, 06/04/21, 12:47:05 PM: 
    Getting paginated list of issues...

Fri, 06/04/21, 12:47:05 PM: 
        Complete!

Fri, 06/04/21, 12:47:05 PM: 
    Getting paginated list of pull requests...

Fri, 06/04/21, 12:47:05 PM: 
        Complete!

Fri, 06/04/21, 12:47:05 PM: 
    Getting issue data...

Fri, 06/04/21, 12:47:44 PM: 
        Complete!

Fri, 06/04/21, 12:47:44 PM: 
    Writing list of issue data to JSON...

Fri, 06/04/21, 12:47:44 PM: 
        Complete!

Fri, 06/04/21, 12:47:44 PM: 
    Getting pull request data...

Fri, 06/04/21, 12:48:16 PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 916, in get_PR_info
    pr_author_name  = cur_pr_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 59481467.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 01:10:16 PM: 
    Getting more pull request info...

Fri, 06/04/21, 01:11:12 PM: 
        Complete!

Fri, 06/04/21, 01:11:12 PM: 
    Writing list of PR data to JSON...

Fri, 06/04/21, 01:11:12 PM: 
        Complete!

Fri, 06/04/21, 01:11:12 PM: 
    Getting commit data...

Fri, 06/04/21, 01:11:31 PM: 
        Complete!

Fri, 06/04/21, 01:11:31 PM: 
    Writing list of commit data to JSON...

Fri, 06/04/21, 01:11:31 PM: 
        Complete!

Fri, 06/04/21, 01:11:31 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 01:21:31 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f42a4fe1e80>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 01:21:33 PM: 
Attempting program start...

Fri, 06/04/21, 01:21:33 PM: 
    Reading pull request data JSON...

Fri, 06/04/21, 01:21:33 PM: 
        Complete!

Fri, 06/04/21, 01:21:33 PM: 
    Reading commit data JSON...

Fri, 06/04/21, 01:21:33 PM: 
        Complete!

Fri, 06/04/21, 01:21:33 PM: 
    Reading issue data JSON...

Fri, 06/04/21, 01:21:33 PM: 
        Complete!

Fri, 06/04/21, 01:21:33 PM: 
    Writing "PR" type CSV...

Fri, 06/04/21, 01:21:33 PM: 
        Complete!

Fri, 06/04/21, 01:21:33 PM: 
    Writing "commit" type CSV...

Fri, 06/04/21, 01:21:33 PM: 
        Complete!

Fri, 06/04/21, 01:21:33 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 01:48:20 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f15bd0e1100>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 01:48:25 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 121, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 258, in exe_menu
    op_choice = input( prog_intro )
KeyboardInterrupt

Fri, 06/04/21, 01:48:25 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 01:53:45 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f6f29ad4100>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 01:53:47 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 121, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 258, in exe_menu
    op_choice = input( prog_intro )
KeyboardInterrupt

Fri, 06/04/21, 01:53:47 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 03:57:34 PM.039:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f2d47eb4040>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 03:58:04 PM.457: 
Attempting program start...

Fri, 06/04/21, 03:58:04 PM.457: 
    Reading pull request data JSON...

Fri, 06/04/21, 03:58:04 PM.458: 
        Complete!

Fri, 06/04/21, 03:58:04 PM.458: 
    Reading commit data JSON...

Fri, 06/04/21, 03:58:04 PM.461: 
        Complete!

Fri, 06/04/21, 03:58:04 PM.461: 
    Writing "commit" type CSV...

Fri, 06/04/21, 03:58:04 PM.473: 
        Complete!

Fri, 06/04/21, 03:58:04 PM.473: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 03:58:28.149:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7ff1d86f7070>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 03:58:38.337: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 100, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 237, in exe_menu
    op_choice = input( prog_intro )
KeyboardInterrupt

Fri, 06/04/21, 03:58:38.338: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Fri, 06/04/21, 04:01:46.%f:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7fd8374b2040>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Fri, 06/04/21, 04:02:57.%f: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 100, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 237, in exe_menu
    op_choice = input( prog_intro )
KeyboardInterrupt

Fri, 06/04/21, 04:02:57.%f: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:33:12 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f2a6b870190>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:33:13 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 105, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 261, in exe_menu
    log_and_print( "PROG_START", "INFO", logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 1079, in log_and_print
    logger.info( out_msg %BKGRN + RST )
TypeError: not all arguments converted during string formatting

Sat, 06/05/21, 08:33:13 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:34:10 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f71a4e69190>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:34:11 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 105, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 261, in exe_menu
    log_and_print( "PROG_START", "INFO", logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 1079, in log_and_print
    logger.info( out_msg %(BKGRN) + RST )
TypeError: not all arguments converted during string formatting

Sat, 06/05/21, 08:34:11 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:52:26 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7ff4c7ca7190>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:52:27 PM: 
Attempting program start...

Sat, 06/05/21, 08:52:28 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:52:28 PM: Complete!

Sat, 06/05/21, 08:52:28 PM: 
    Getting issue data...

Sat, 06/05/21, 08:52:34 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 105, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 269, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 557, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:52:34 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:53:32 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7fbd184181f0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:53:33 PM: 
Attempting program start...

Sat, 06/05/21, 08:53:33 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:53:33 PM: Complete!

Sat, 06/05/21, 08:53:33 PM: 
    Getting issue data...

Sat, 06/05/21, 08:53:37 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 105, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 269, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 558, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:53:37 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:56:01 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7ff9df4122e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:56:09 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 243, in exe_menu
    op_choice = input( prog_intro )
KeyboardInterrupt

Sat, 06/05/21, 08:56:09 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:57:04 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7fb6b7e44310>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:57:07 PM: 
Attempting program start...

Sat, 06/05/21, 08:57:07 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:57:07 PM: Complete!

Sat, 06/05/21, 08:57:07 PM: 
    Getting issue data...

Sat, 06/05/21, 08:57:10 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 560, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:57:10 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:57:50 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f43cf04d310>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:57:52 PM: 
Attempting program start...

Sat, 06/05/21, 08:57:52 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:57:52 PM: Complete!

Sat, 06/05/21, 08:57:52 PM: 
    Getting issue data...

Sat, 06/05/21, 08:58:02 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 537, in get_issue_info
    cur_issue         = issue_paged_list[index]
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:58:02 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:58:05 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f0f79b02310>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:58:06 PM: 
Attempting program start...

Sat, 06/05/21, 08:58:06 PM: 
    Getting paginated list of pull requests...

Sat, 06/05/21, 08:58:06 PM: Complete!

Sat, 06/05/21, 08:58:08 PM: 
    Getting pull request data...

Sat, 06/05/21, 08:58:10 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 279, in exe_menu
    write_pr_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 1443, in write_pr_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 908, in get_PR_info
    most_recent_commit = pr_commits[last_commit_position]
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 48, in __getitem__
    self.__fetchToIndex(index)
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 64, in __fetchToIndex
    self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:58:10 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:58:37 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7fe7740572e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:58:39 PM: 
Attempting program start...

Sat, 06/05/21, 08:58:39 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:58:39 PM: Complete!

Sat, 06/05/21, 08:58:39 PM: 
    Getting issue data...

Sat, 06/05/21, 08:58:43 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 564, in get_issue_info
    for comment in comments_paged_list:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:58:43 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 08:58:48 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f5428e062e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 08:58:49 PM: 
Attempting program start...

Sat, 06/05/21, 08:58:49 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 08:58:49 PM: Complete!

Sat, 06/05/21, 08:58:50 PM: 
    Getting issue data...

Sat, 06/05/21, 08:58:55 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 560, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 08:58:55 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 09:05:29 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7fd786b872e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 09:05:30 PM: 
Attempting program start...

Sat, 06/05/21, 09:05:30 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 09:05:30 PM:  Complete!

Sat, 06/05/21, 09:05:30 PM: 
    Getting issue data...

Sat, 06/05/21, 09:05:34 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 543, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 09:05:34 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 09:05:41 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f54d23792e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 09:05:42 PM: 
Attempting program start...

Sat, 06/05/21, 09:05:42 PM: 
    Getting paginated list of pull requests...

Sat, 06/05/21, 09:05:42 PM:  Complete! 

Sat, 06/05/21, 09:05:43 PM: 
    Getting pull request data...

Sat, 06/05/21, 09:05:46 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 279, in exe_menu
    write_pr_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 1443, in write_pr_commit_json
    pr_info_metalist, commits_paged_list = get_PR_info( session, pr_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 901, in get_PR_info
    if pr_commits.totalCount > 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 09:05:46 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------


Sat, 06/05/21, 09:05:55 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/jabref/jabref_100.txt
        - repo             : JabRef/jabref
        - session          : <github.MainClass.Github object at 0x7f802f9532e0>
        - rows             : 100
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/jabref/jabref_100_log.txt        

        - issue json file  : outputs/jabref_100/jabref_100_issue_list.json
        - pr JSON file     : outputs/jabref_100/jabref_100_pr_list.json
        - commit JSON file : outputs/jabref_100/jabref_100_commit_list.json

        - "pr" CSV file    : outputs/jabref_100/jabref_100_pr_output.csv       
        - "commit" CSV file: outputs/jabref_100/jabref_100_commit_output.csv


Sat, 06/05/21, 09:05:58 PM: 
Attempting program start...

Sat, 06/05/21, 09:05:58 PM: 
    Getting paginated list of issues...

Sat, 06/05/21, 09:05:58 PM:  Complete! 

Sat, 06/05/21, 09:05:58 PM: 
    Getting issue data...

Sat, 06/05/21, 09:06:10 PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 107, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 271, in exe_menu
    issue_metalist = get_issue_info( session, issue_paged_list,
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 543, in get_issue_info
    issue_name_str  = cur_issue_user.name
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

Sat, 06/05/21, 09:06:10 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------

